name: Testing

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  NEXT_PUBLIC_SENTRY_ENVIRONMENT: test
  API_URL: https://api.gitpoap.io:443

jobs:
  run-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: yarn install

      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
          cache: yarn
      - run: yarn install --frozen-lockfile --check-files
      - name: Test Bot
        run: yarn test
